name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}} | sed -En 's/.*\[test\-(.*|\ .*)\]/\1/p' | awk '{$1=$1;print}')
          echo "TEST_TAG=${MSG}" >> $GITHUB_ENV
      - name: Echo commit message
        run: |
          echo "Commit SHA: ${{github.event.after}}, commit message: ${TEST_TAG}"
      - name: Get type of the test
        id: type_of_test
        run: |
          TEST_TYPE="$(echo $TEST_TAG | grep -P '^[^-]*' -o)"
          echo "TYPE_OF_TEST=${TEST_TYPE}" >> $GITHUB_OUTPUT
      - name: Get the file name
        id: file_name
        run: |
          FILE_NAME="$(echo $TEST_TAG | grep -P '(?<=-).*' -o)"
          echo "NAME_OF_FILE=${FILE_NAME}" >> $GITHUB_OUTPUT
          echo "${{ steps.type-of-test.outputs.MORE }}"

    outputs:
      test_type: "${{steps.type_of_test.outputs.TYPE_OF_TEST}}"
      file_name: $( echo "${{steps.file_name.outputs.NAME_OF_FILE }}" )

  run_cypress:
    needs: send_notification
    name: What a wow
    runs-on: ubuntu-20.04
    steps:
      - name: Jinglis Boda
        run: |
          echo "${{ needs.send_notification.outputs.test_type }}"
